services:
  - type: web
    name: lottery-display
    runtime: node
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install --prefix client && npm run build --prefix client && NPM_CONFIG_PRODUCTION=false npm install --prefix server
    startCommand: npm run start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: LOTTERY_DATA_DIR
        value: ./data
      - key: ADMIN_PASSPHRASE
        sync: false
